# Generated by Django 2.1.2 on 2018-11-25 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='Notes/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='Not Selected', max_length=30)),
                ('subject', models.CharField(choices=[('Subject1', 'Subject1'), ('Subject2', 'Subject2'), ('Subject3', 'Subject3'), ('Subject4', 'Subject4')], default='Others', max_length=20)),
                ('notes', models.TextField(default='no descripiton')),
                ('slug', models.SlugField(unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='noteimages',
            name='note',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='notes.Notes'),
        ),
    ]
