# Generated by Django 2.1.2 on 2018-11-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20181125_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteimages',
            name='note',
        ),
        migrations.AddField(
            model_name='notes',
            name='image',
            field=models.ImageField(null=True, upload_to='Notes/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='notes',
            name='image1',
            field=models.ImageField(null=True, upload_to='Notes/', verbose_name='image1'),
        ),
        migrations.AddField(
            model_name='notes',
            name='image2',
            field=models.ImageField(null=True, upload_to='Notes/', verbose_name='image2'),
        ),
        migrations.AddField(
            model_name='notes',
            name='image3',
            field=models.ImageField(null=True, upload_to='Notes/', verbose_name='image3'),
        ),
        migrations.DeleteModel(
            name='NoteImages',
        ),
    ]
