# Generated by Django 2.1.2 on 2018-11-18 13:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0002_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='.', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Electronics', 'Electronics'), ('Books', 'Books'), ('Services', 'Services'), ('Others', 'Others')], default='Others', max_length=2), size=None)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.upload_location)),
                ('description', models.TextField(default='no descripiton')),
                ('slug', models.SlugField(unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
